### ISSUE TITLE
Update build process to refresh stats in README

### ISSUE THREAD

**Issue by zeke** [nice-registry/all-the-package-repos#27]
There used to be a part of the build process that updates the stats in the README:

```
<!-- stats -->
Packages | Count | Percentage
-------- | ----- | ----------
With repository in package.json | 824259 | 100%
On GitHub | 809594 |  98.22%
On BitBucket | 658 |  0.08%
On GitLab | 1014 |  0.12%
<!-- /stats -->
```

But it looks that has been disabled or removed, and now that table is out of date. Let's add it back.

cc @eridal who might have some context. No pressure to work on this!

**Comment by eridal** [comment]
Hey @zeke, 

Oh yeah, I never updated the part that writes the readme, but at least those stats are being stored at the metadata, [here is an example](https://github.com/nice-registry/all-the-package-repos/blob/e1fa3f578032243359dc6679d3593c2743c43420/data/metadata.json#L14-L19)

I think the solution is to add a section to overwrite those values at the readme, the right place will be in the [`writeChanges`](https://github.com/nice-registry/all-the-package-repos/blob/e1fa3f578032243359dc6679d3593c2743c43420/scripts/update.js#L428) function, an additional step like `writeReadme` just after the [`writeCache`](https://github.com/nice-registry/all-the-package-repos/blob/e1fa3f578032243359dc6679d3593c2743c43420/scripts/update.js#L439) step would do the trick.

Let me know if you want to take care, otherwise I think I could find some time for later this week

**Comment by zeke** [comment]
I might not be able to get to this for a while. If you have the time and interest, please go for it!
